// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:OrganizerCompanion.Core.Models.Domain.Account.#ctor(System.Int32,System.String,System.String,System.Int32,System.String,OrganizerCompanion.Core.Interfaces.Domain.IDomainEntity,System.Collections.Generic.List{OrganizerCompanion.Core.Interfaces.Domain.IAccountFeature},System.DateTime,System.Nullable{System.DateTime},System.Nullable{System.Boolean},System.Nullable{System.Int32},System.String)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:OrganizerCompanion.Core.Models.Domain.CAAddress.#ctor(System.Int32,System.String,System.String,System.String,OrganizerCompanion.Core.Interfaces.Type.INationalSubdivision,System.String,System.String,OrganizerCompanion.Core.Enums.Types,System.DateTime,System.Nullable{System.DateTime},System.Nullable{System.Boolean},System.Nullable{System.Int32},System.String)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:OrganizerCompanion.Core.Models.Domain.Email.#ctor(System.Int32,System.String,System.Nullable{OrganizerCompanion.Core.Enums.Types},System.DateTime,System.Nullable{System.DateTime},System.Nullable{System.Boolean},System.Nullable{System.Int32},System.String)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:OrganizerCompanion.Core.Models.Domain.Feature.#ctor(System.Int32,System.String,System.Boolean,System.Boolean,System.Int32,System.String,System.DateTime,System.Nullable{System.DateTime})")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:OrganizerCompanion.Core.Models.Domain.MXAddress.#ctor(System.Int32,System.String,System.String,System.String,System.String,OrganizerCompanion.Core.Interfaces.Type.INationalSubdivision,System.String,OrganizerCompanion.Core.Enums.Types,System.DateTime,System.Nullable{System.DateTime},System.Nullable{System.Boolean},System.Nullable{System.Int32},System.String)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:OrganizerCompanion.Core.Models.Domain.Organization.#ctor(System.Int32,System.String,System.Collections.Generic.List{OrganizerCompanion.Core.Interfaces.Domain.IAddress},System.Collections.Generic.List{OrganizerCompanion.Core.Interfaces.Domain.IPhoneNumber},System.Collections.Generic.List{OrganizerCompanion.Core.Interfaces.Domain.IPerson},System.Collections.Generic.List{OrganizerCompanion.Core.Interfaces.Domain.IPerson},System.Collections.Generic.List{OrganizerCompanion.Core.Interfaces.Domain.IAccount},System.DateTime,System.Nullable{System.DateTime},System.Nullable{System.Boolean},System.Nullable{System.Int32},System.String)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:OrganizerCompanion.Core.Models.Domain.Password.#ctor(System.Int32,System.String,System.String,System.Int32,OrganizerCompanion.Core.Interfaces.Domain.IAccount,System.DateTime,System.Nullable{System.DateTime},System.Nullable{System.Boolean},System.Nullable{System.Int32},System.String)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:OrganizerCompanion.Core.Models.Domain.PhoneNumber.#ctor(System.Int32,System.String,System.Nullable{OrganizerCompanion.Core.Enums.Types},System.DateTime,System.Nullable{System.DateTime},System.Nullable{System.Boolean},System.Nullable{System.Int32},System.String)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:OrganizerCompanion.Core.Models.Domain.USAddress.#ctor(System.Int32,System.String,System.String,System.String,OrganizerCompanion.Core.Interfaces.Type.INationalSubdivision,System.String,System.String,System.Nullable{OrganizerCompanion.Core.Enums.Types},System.DateTime,System.Nullable{System.DateTime},System.Nullable{System.Boolean},System.Nullable{System.Int32},System.String)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:OrganizerCompanion.Core.Models.Domain.User.#ctor(System.Int32,System.String,System.String,System.String,System.String,System.Nullable{OrganizerCompanion.Core.Enums.Pronouns},System.Nullable{System.DateTime},System.Nullable{System.DateTime},System.Nullable{System.DateTime},System.Collections.Generic.List{OrganizerCompanion.Core.Interfaces.Domain.IEmail},System.Collections.Generic.List{OrganizerCompanion.Core.Interfaces.Domain.IPhoneNumber},System.Collections.Generic.List{OrganizerCompanion.Core.Interfaces.Domain.IAddress},System.Nullable{System.Boolean},System.Nullable{System.Boolean},System.Nullable{System.Boolean},System.Nullable{System.Boolean},System.DateTime,System.Nullable{System.DateTime},System.Nullable{System.Boolean},System.Nullable{System.Int32},System.String)")]
